[
   JSModule                                       -- _1,
   JSModule.1:iter-star                           -- _1,
   JSVarDeclNoInit                                -- KW["var"] _1 KW[";"],
   JSVarDeclNoInit.1:iter-star-sep                -- _1 KW[","],
   JSVarDecl                                      -- KW["var"] _1 KW["="] _2 KW[";"],
   JSFor                                          -- KW["for"] KW["("] _1 _2 KW[";"] _3 KW[")"] _4,
   JSForIn                                        -- KW["for"] KW["("] KW["var"] _1 KW["in"] _2 KW[")"] _3,
   JSIf                                           -- KW["if"] KW["("] _1 KW[")"] _2 KW["else"] _3,
   JSIfNoElse                                     -- KW["if"] KW["("] _1 KW[")"] _2,
   JSWhile                                        -- KW["while"] KW["("] _1 KW[")"] _2,
   JSTryCatch                                     -- KW["try"] KW["{"] _1 KW["}"] KW["catch"] KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   JSTryCatch.1:iter-star                         -- _1,
   JSTryCatch.3:iter-star                         -- _1,
   JSSwitch                                       -- KW["switch"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   JSSwitch.2:iter-star                           -- _1,
   JSCase                                         -- KW["case"] _1 KW[":"] _2,
   JSCase.2:iter-star                             -- _1,
   JSDefaultCase                                  -- V  [H  [KW["default"] KW[":"]] _1],
   JSDefaultCase.1:iter-star                      -- _1,
   JSBreak                                        -- KW["break"] KW[";"],
   JSThrow                                        -- KW["throw"] _1 KW[";"],
   JSReturn                                       -- KW["return"] _1 KW[";"],
   JSReturn                                       -- KW["return"] KW[";"],
   JSDelete                                       -- KW["delete"] _1 KW[";"],
   JSExpStat                                      -- _1 KW[";"],
   JSBlock                                        -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   JSBlock.1:iter-star                            -- _1,
   JSFunctionDecl                                 -- KW["function"] _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   JSFunctionDecl.2:iter-star-sep                 -- _1 KW[","],
   JSFunctionDecl.3:iter-star                     -- _1,
   JSAsyncFunctionDecl                            -- KW["function"] _1 KW["~("] _2 KW[")"] KW["{"] _3 KW["}"],
   JSAsyncFunctionDecl.2:iter-star-sep            -- _1 KW[","],
   JSAsyncFunctionDecl.3:iter-star                -- _1,
   JSLFieldAccess                                 -- _1 KW["."] _2,
   JSLVar                                         -- _1,
   JSLPropAccess                                  -- _1 KW["["] _2 KW["]"],
   JSRegex                                        -- KW["/"] _1 KW["/"] _2,
   JSRegex.2:opt                                  -- _1,
   JSStringLit                                    -- _1,
   JSIntLit                                       -- _1,
   JSIntLit                                       -- _1,
   JSVar                                          -- _1,
   JSTrue                                         -- KW["true"],
   JSFalse                                        -- KW["false"],
   JSThis                                         -- KW["this"],
   JSNull                                         -- KW["null"],
   JSAssign                                       -- _1 _2 _3,
   JSArrayCons                                    -- KW["["] _1 KW["]"],
   JSArrayCons.1:iter-star-sep                    -- _1 KW[","],
   JSNew                                          -- KW["new"] _1 KW["("] _2 KW[")"],
   JSNew.2:iter-star-sep                          -- _1 KW[","],
   JSObj                                          -- KW["{"] _1 KW["}"],
   JSObj.1:iter-star-sep                          -- _1 KW[","],
   JSPropVal                                      -- _1 KW[":"] _2,
   JSPropVal                                      -- _1 KW[":"] _2,
   JSInc                                          -- _1 KW["++"],
   JSDec                                          -- _1 KW["--"],
   JSNot                                          -- KW["!"] _1,
   JSTypeOf                                       -- KW["typeof"] _1,
   JSIn                                           -- _1 KW["in"] _2,
   JSChoice                                       -- _1 KW["?"] _2 KW[":"] _3,
   JSBracket                                      -- KW["("] _1 KW[")"],
   JSOp                                           -- _1 _2 _3,
   JSOp                                           -- _1 _2 _3,
   JSOp                                           -- _1 _2 _3,
   JSOp                                           -- _1 _2 _3,
   JSFieldAccess                                  -- _1 KW["."] _2,
   JSCall                                         -- _1 KW["("] _2 KW[")"],
   JSCall.2:iter-star-sep                         -- _1 KW[","],
   JSAsyncCall                                    -- _1 KW["~("] _2 KW[")"],
   JSAsyncCall.2:iter-star-sep                    -- _1 KW[","],
   JSPropAccess                                   -- _1 _2,
   JSIndex                                        -- KW["["] _1 KW["]"],
   JSFunctionExp                                  -- KW["function"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   JSFunctionExp.1:iter-star-sep                  -- _1 KW[","],
   JSFunctionExp.2:iter-star                      -- _1,
   JSAsyncFunctionExp                             -- KW["function"] KW["~("] _1 KW[")"] KW["{"] _2 KW["}"],
   JSAsyncFunctionExp.1:iter-star-sep             -- _1 KW[","],
   JSAsyncFunctionExp.2:iter-star                 -- _1,
   ServerApplication                              -- KW["server"] _1 _2 _3,
   ServerApplication.2:iter-star                  -- _1,
   ServerApplication.3:iter-star                  -- _1,
   DatabaseSetting                                -- KW["database"] KW["host"] _1 KW["name"] _2 KW["username"] _3 KW["password"] _4,
   DebugSetting                                   -- KW["debug"],
   ServiceAnno                                    -- KW["@service"] _1 _2,
   SocketEventAnno                                -- KW["@socketevent"] KW["("] _1 KW[")"],
   GetMethod                                      -- KW["GET"],
   PostMethod                                     -- KW["POST"],
   PutMethod                                      -- KW["PUT"],
   DeleteMethod                                   -- KW["DELETE"],
   MiddlewareUse                                  -- KW["middleware"] _1,
   Configuration                                  -- V  [H  [KW["configuration"]] _1],
   Configuration.1:iter-star                      -- _1,
   TitleSetting                                   -- KW["title"] _1,
   DatabaseSetting                                -- KW["database"] _1,
   IconSetting                                    -- KW["icon"] _1,
   VersionSetting                                 -- KW["version"] _1,
   StdLibSetting                                  -- KW["stdlib"] _1,
   LibSetting                                     -- KW["lib"] _1,
   HtmlSetting                                    -- KW["html"] _1,
   OutputSetting                                  -- KW["output"] _1,
   ReleaseOutputSetting                           -- KW["release"] KW["output"] _1,
   OfflineSetting                                 -- KW["offline"],
   DebugSetting                                   -- KW["debug"],
   LoadingHtmlSetting                             -- KW["loadingHTML"] _1,
   StyleVarSetting                                -- KW["style"] _1 KW["="] _2,
   NativeSettings                                 -- KW["native"] KW["{"] _1 KW["}"],
   NativeSettings.1:iter-star                     -- _1,
   buildfarmUsername                              -- KW["username"] _1,
   buildfarmPassword                              -- KW["password"] _1,
   buildfarmPlatforms                             -- V  [H  [KW["platforms"]] _1],
   buildfarmPlatforms.1:iter-star-sep             -- _1 KW[","],
   Style                                          -- _1 KW["style"] _2 KW["{"] _3 KW["}"],
   Style.1:iter-star                              -- _1,
   Style.2:iter                                   -- _1,
   Style.3:iter-star                              -- _1,
   StyleMixin                                     -- _1 KW["style"] KW["mixin"] _2 KW["("] _3 KW[")"] KW["{"] _4 KW["}"],
   StyleMixin.1:iter-star                         -- _1,
   StyleMixin.3:iter-star-sep                     -- _1 KW[","],
   StyleMixin.4:iter-star                         -- _1,
   StyleFArg                                      -- KW["$"] _1,
   StyleVarDecl                                   -- KW["style"] _1 KW["="] _2,
   StyleVar                                       -- KW["$"] _1,
   ExternalStyle                                  -- _1 KW["external"] KW["style"] _2,
   ExternalStyle.1:iter-star                      -- _1,
   ExternalStyle.2:iter                           -- _1,
   StyleProperty                                  -- _1 KW[":"] _2 KW[";"],
   StyleMixinCall                                 -- _1 KW["("] _2 KW[")"] KW[";"],
   StyleMixinCall.2:iter-star-sep                 -- _1 KW[","],
   StyleElemRecover                               -- _1 KW[";"],
   StyleSelector                                  -- _1,
   StyleSelectorWithPseudo                        -- _1 KW[":"] _2,
   StyleSelectorWithPseudoArg                     -- _1 KW[":"] _2 KW["("] _3 KW[")"],
   Color                                          -- _1,
   StyleId                                        -- _1,
   String                                         -- _1,
   Num                                            -- _1,
   NumUnit                                        -- _1 _2,
   StylePropVal                                   -- _1 KW["="] _2,
   StyleAdd                                       -- _1 KW["+"] _2,
   StyleSub                                       -- _1 KW["~"] _2,
   StyleMul                                       -- _1 KW["*"] _2,
   StyleFieldAccess                               -- _1 KW["."] _2,
   ImportData                                     -- KW["$data"] KW["("] _1 KW[")"],
   StylePath                                      -- _1 KW["/"] _2,
   StylePath.2:iter-sep                           -- _1 KW["/"],
   StyleCall                                      -- _1 KW["("] _2 KW[")"],
   StyleCall.2:iter-star-sep                      -- _1 KW[","],
   StyleExps                                      -- _1,
   StyleExps.1:iter                               -- _1,
   StyleExpsCS                                    -- _1,
   StyleExpsCS.1:iter-sep                         -- _1 KW[","],
   PxUnit                                         -- KW["px"],
   EmUnit                                         -- KW["em"],
   PtUnit                                         -- KW["pt"],
   SUnit                                          -- KW["s"],
   PercentageUnit                                 -- KW["%"],
   ExternalTypeNoSuper                            -- _1 KW["external"] KW["type"] _2 KW["{"] _3 KW["}"],
   ExternalTypeNoSuper.1:iter-star                -- _1,
   ExternalTypeNoSuper.3:iter-star                -- _1,
   ExternalType                                   -- _1 KW["external"] KW["type"] _2 KW[":"] _3 KW["{"] _4 KW["}"],
   ExternalType.1:iter-star                       -- _1,
   ExternalType.4:iter-star                       -- _1,
   ExternalGenericType                            -- _1 KW["external"] KW["type"] _2 KW["<"] _3 KW[">"] KW["{"] _4 KW["}"],
   ExternalGenericType.1:iter-star                -- _1,
   ExternalGenericType.3:iter-star-sep            -- _1 KW[","],
   ExternalGenericType.4:iter-star                -- _1,
   ExternalStaticMethod                           -- _1 KW["static"] KW["function"] _2 KW["("] _3 KW[")"] KW[":"] _4,
   ExternalStaticMethod.1:iter-star               -- _1,
   ExternalStaticMethod.3:iter-star-sep           -- _1 KW[","],
   ExternalMethod                                 -- _1 KW["function"] _2 KW["("] _3 KW[")"] KW[":"] _4,
   ExternalMethod.1:iter-star                     -- _1,
   ExternalMethod.3:iter-star-sep                 -- _1 KW[","],
   ExternalStaticSyncMethod                       -- _1 KW["static"] KW["sync"] KW["function"] _2 KW["("] _3 KW[")"] KW[":"] _4,
   ExternalStaticSyncMethod.1:iter-star           -- _1,
   ExternalStaticSyncMethod.3:iter-star-sep       -- _1 KW[","],
   ExternalSyncMethod                             -- _1 KW["sync"] KW["function"] _2 KW["("] _3 KW[")"] KW[":"] _4,
   ExternalSyncMethod.1:iter-star                 -- _1,
   ExternalSyncMethod.3:iter-star-sep             -- _1 KW[","],
   ExternalControl                                -- _1 KW["external"] KW["control"] _2 KW["("] _3 KW[")"],
   ExternalControl.1:iter-star                    -- _1,
   ExternalControl.3:iter-star-sep                -- _1 KW[","],
   ExternalScreen                                 -- _1 KW["external"] KW["screen"] _2 KW["("] _3 KW[")"] KW[":"] _4,
   ExternalScreen.1:iter-star                     -- _1,
   ExternalScreen.3:iter-star-sep                 -- _1 KW[","],
   ExternalEntity                                 -- _1 KW["external"] KW["entity"] _2 KW[":"] _3 KW["{"] _4 KW["}"],
   ExternalEntity.1:iter-star                     -- _1,
   ExternalEntity.4:iter-star                     -- _1,
   ExternalFunction                               -- _1 KW["external"] KW["function"] _2 KW["("] _3 KW[")"] KW[":"] _4,
   ExternalFunction.1:iter-star                   -- _1,
   ExternalFunction.3:iter-star-sep               -- _1 KW[","],
   ExternalSyncFunction                           -- _1 KW["external"] KW["sync"] KW["function"] _2 KW["("] _3 KW[")"] KW[":"] _4,
   ExternalSyncFunction.1:iter-star               -- _1,
   ExternalSyncFunction.3:iter-star-sep           -- _1 KW[","],
   ExternalVarDecl                                -- KW["external"] KW["var"] _1 KW[":"] _2 KW[";"],
   ExternalControl                                -- _1 KW["external"] KW["template"] _2 KW["("] _3 KW[")"],
   ExternalControl.1:iter-star                    -- _1,
   ExternalControl.3:iter-star-sep                -- _1 KW[","],
   RegExp                                         -- KW["/"] _1 KW["/"] _2,
   SingleBranch                                   -- _1,
   TupleBranch                                    -- _1 KW["|"] _2,
   Pieces                                         -- _1,
   Pieces.1:iter                                  -- _1,
   SingleAtom                                     -- _1,
   QuantifiedAtom                                 -- _1 _2,
   GreedyExactBound                               -- KW["{"] _1 KW["}"],
   GreedyLowerBound                               -- KW["{"] _1 KW[","] KW["}"],
   GreedyLowerUpperBound                          -- KW["{"] _1 KW[","] _2 KW["}"],
   GreedyOnceOrNot                                -- KW["?"],
   GreedyZeroOrMore                               -- KW["*"],
   GreedyOneOrMore                                -- KW["+"],
   ReluctantExactBound                            -- KW["{"] _1 KW["}?"],
   ReluctantLowerBound                            -- KW["{"] _1 KW[","] KW["}?"],
   ReluctantLowerUpperBound                       -- KW["{"] _1 KW[","] _2 KW["}?"],
   ReluctantOnceOrNot                             -- KW["??"],
   ReluctantZeroOrMore                            -- KW["*?"],
   ReluctantOneOrMore                             -- KW["+?"],
   PossessiveExactBound                           -- KW["{"] _1 KW["}+"],
   PossessiveLowerBound                           -- KW["{"] _1 KW[","] KW["}+"],
   PossessiveLowerUpperBound                      -- KW["{"] _1 KW[","] _2 KW["}+"],
   PossessiveOnceOrNot                            -- KW["?+"],
   PossessiveZeroOrMore                           -- KW["*+"],
   PossessiveOneOrMore                            -- KW["++"],
   Capture                                        -- KW["("] _1 KW[")"],
   NonCapture                                     -- KW["(?:"] _1 KW[")"],
   PositiveLookahead                              -- KW["(?="] _1 KW[")"],
   NegativeLookahead                              -- KW["(?!"] _1 KW[")"],
   PositiveLookbehind                             -- KW["(?<="] _1 KW[")"],
   NegativeLookbehind                             -- KW["(?<!"] _1 KW[")"],
   PythonCapture                                  -- KW["(?P<"] _1 KW[">"] _2 KW[")"],
   RegexCapture                                   -- KW["("] _1 KW[")@{"] _2 KW["}"],
   Empty                                          -- KW["()"],
   SingleCharacter                                -- KW["."],
   LineStart                                      -- KW["^"],
   LineEnd                                        -- KW["$"],
   CharacterClass                                 -- _1,
   AtomLiteral                                    -- _1,
   AtomCharacter                                  -- _1,
   QuotedAtom                                     -- KW["\\Q"] _1 KW["\\E"],
   BracketList                                    -- V  [V vs=2 [KW["["] _1] KW["]"]],
   BracketList.1:iter                             -- _1,
   NegatedBracketList                             -- V  [V vs=2 [KW["[^"] _1] KW["]"]],
   NegatedBracketList.1:iter                      -- _1,
   Range                                          -- _1 KW["-"] _2,
   Range.1:alt                                    -- _1 _2,
   Range.2:alt                                    -- _1 _2,
   Union                                          -- _1,
   BracketLiteral                                 -- _1,
   BracketCharacter                               -- _1,
   LowerClass                                     -- KW["Lower"],
   UpperClass                                     -- KW["Upper"],
   ASCIIClass                                     -- KW["ASCII"],
   AlphaClass                                     -- KW["Alpha"],
   DigitClass                                     -- KW["Digit"],
   AlnumClass                                     -- KW["Alnum"],
   PunctClass                                     -- KW["Punct"],
   GraphClass                                     -- KW["Graph"],
   PrintClass                                     -- KW["Print"],
   BlankClass                                     -- KW["Blank"],
   CntrlClass                                     -- KW["Cntrl"],
   XDigitClass                                    -- KW["XDigit"],
   WhiteSpace                                     -- KW["Space"],
   JavaIsLowerCase                                -- KW["javaLowerCase"],
   JavaIsLowerCase                                -- KW["javaUpperCase"],
   JavaIsWhitespace                               -- KW["javaWhitespace"],
   JavaIsMirrored                                 -- KW["javaMirrored"],
   GreekBlock                                     -- KW["InGreek"],
   UppercaseLetter                                -- KW["Lu"],
   CurrencySymbol                                 -- KW["Sc"],
   DoubleQuote                                    -- KW["\""],
   DoubleQuote                                    -- KW["\""],
   OctalChar                                      -- KW["\\0"] _1,
   HexHexChar                                     -- KW["\\x"] _1,
   DecHexChar                                     -- KW["\\u"] _1,
   Tab                                            -- KW["\\t"],
   Newline                                        -- KW["\\n"],
   Return                                         -- KW["\\r"],
   Formfeed                                       -- KW["\\f"],
   Alarm                                          -- KW["\\a"],
   Escape                                         -- KW["\\e"],
   WordChar                                       -- KW["\\w"],
   NonWordChar                                    -- KW["\\W"],
   WhiteSpaceChar                                 -- KW["\\s"],
   NonWhiteSpaceChar                              -- KW["\\S"],
   DigitChar                                      -- KW["\\d"],
   NonDigitChar                                   -- KW["\\D"],
   ControlCharacter                               -- KW["\\c"] _1,
   WordBoundry                                    -- KW["\\b"],
   NonWordBoundry                                 -- KW["\\B"],
   InputBeginBoundry                              -- KW["\\A"],
   PrevMatchEndBoundry                            -- KW["\\G"],
   EndInputBoundry                                -- KW["\\Z"],
   EndInputFinalBoundry                           -- KW["\\z"],
   BackReference                                  -- KW["\\"] _1,
   Space                                          -- KW["\\ "],
   Tab                                            -- KW["\\\t"],
   Newline                                        -- KW["\\\n"],
   OctalChar                                      -- KW["\\0"] _1,
   HexHexChar                                     -- KW["\\x"] _1,
   DecHexChar                                     -- KW["\\u"] _1,
   Tab                                            -- KW["\\t"],
   Newline                                        -- KW["\\n"],
   Return                                         -- KW["\\r"],
   Formfeed                                       -- KW["\\f"],
   Alarm                                          -- KW["\\a"],
   Escape                                         -- KW["\\e"],
   WordChar                                       -- KW["\\w"],
   NonWordChar                                    -- KW["\\W"],
   WhiteSpaceChar                                 -- KW["\\s"],
   NonWhiteSpaceChar                              -- KW["\\S"],
   DigitChar                                      -- KW["\\d"],
   NonDigitChar                                   -- KW["\\D"],
   ControlCharacter                               -- KW["\\c"] _1,
   WordBoundry                                    -- KW["\\b"],
   NonWordBoundry                                 -- KW["\\B"],
   InputBeginBoundry                              -- KW["\\A"],
   PrevMatchEndBoundry                            -- KW["\\G"],
   EndInputBoundry                                -- KW["\\Z"],
   EndInputFinalBoundry                           -- KW["\\z"],
   BackReference                                  -- KW["\\"] _1,
   Space                                          -- KW["\\ "],
   Tab                                            -- KW["\\\t"],
   Newline                                        -- KW["\\\n"],
   Quoted                                         -- KW["\\"] _1,
   Quoted                                         -- KW["\\"] _1,
   DoubleQuote                                    -- KW["\""],
   DoubleQuote                                    -- KW["\""],
   RegexId                                        -- _1,
   TypeNoSuper                                    -- _1 KW["type"] _2 KW["{"] _3 KW["}"],
   TypeNoSuper.1:iter-star                        -- _1,
   TypeNoSuper.3:iter-star                        -- _1,
   Type                                           -- _1 KW["type"] _2 KW[":"] _3 KW["{"] _4 KW["}"],
   Type.1:iter-star                               -- _1,
   Type.4:iter-star                               -- _1,
   Service                                        -- _1 KW["service"] _2 KW["{"] _3 KW["}"],
   Service.1:iter-star                            -- _1,
   Service.3:iter-star                            -- _1,
   Resource                                       -- _1 KW["resource"] _2 KW["("] _3 KW[")"] KW[":"] _4 KW["{"] _5 KW["}"],
   Resource.1:iter-star                           -- _1,
   Resource.3:iter-star-sep                       -- _1 KW[","],
   Resource.5:iter-star                           -- _1,
   Function                                       -- _1 KW["function"] _2 KW["("] _3 KW[")"] KW[":"] _4 KW["{"] _5 KW["}"],
   Function.1:iter-star                           -- _1,
   Function.3:iter-star-sep                       -- _1 KW[","],
   Function.5:iter-star                           -- _1,
   FunctionNoReturnType                           -- _1 KW["function"] _2 KW["("] _3 KW[")"] KW["{"] _4 KW["}"],
   FunctionNoReturnType.1:iter-star               -- _1,
   FunctionNoReturnType.3:iter-star-sep           -- _1 KW[","],
   FunctionNoReturnType.4:iter-star               -- _1,
   SyncFunction                                   -- _1 KW["sync"] KW["function"] _2 KW["("] _3 KW[")"] KW[":"] _4 KW["{"] _5 KW["}"],
   SyncFunction.1:iter-star                       -- _1,
   SyncFunction.3:iter-star-sep                   -- _1 KW[","],
   SyncFunction.5:iter-star                       -- _1,
   SyncFunctionNoReturnType                       -- _1 KW["sync"] KW["function"] _2 KW["("] _3 KW[")"] KW["{"] _4 KW["}"],
   SyncFunctionNoReturnType.1:iter-star           -- _1,
   SyncFunctionNoReturnType.3:iter-star-sep       -- _1 KW[","],
   SyncFunctionNoReturnType.4:iter-star           -- _1,
   StaticFunction                                 -- _1 KW["static"] KW["function"] _2 KW["("] _3 KW[")"] KW[":"] _4 KW["{"] _5 KW["}"],
   StaticFunction.1:iter-star                     -- _1,
   StaticFunction.3:iter-star-sep                 -- _1 KW[","],
   StaticFunction.5:iter-star                     -- _1,
   StaticFunctionNoReturnType                     -- _1 KW["static"] KW["function"] _2 KW["("] _3 KW[")"] KW["{"] _4 KW["}"],
   StaticFunctionNoReturnType.1:iter-star         -- _1,
   StaticFunctionNoReturnType.3:iter-star-sep     -- _1 KW[","],
   StaticFunctionNoReturnType.4:iter-star         -- _1,
   StaticSyncFunction                             -- _1 KW["static"] KW["sync"] KW["function"] _2 KW["("] _3 KW[")"] KW[":"] _4 KW["{"] _5 KW["}"],
   StaticSyncFunction.1:iter-star                 -- _1,
   StaticSyncFunction.3:iter-star-sep             -- _1 KW[","],
   StaticSyncFunction.5:iter-star                 -- _1,
   StaticSyncFunctionNoReturnType                 -- _1 KW["static"] KW["sync"] KW["function"] _2 KW["("] _3 KW[")"] KW["{"] _4 KW["}"],
   StaticSyncFunctionNoReturnType.1:iter-star     -- _1,
   StaticSyncFunctionNoReturnType.3:iter-star-sep -- _1 KW[","],
   StaticSyncFunctionNoReturnType.4:iter-star     -- _1,
   VarDecl                                        -- KW["var"] _1 KW[":"] _2 KW["="] _3 KW[";"],
   VarDeclInferred                                -- KW["var"] _1 KW["="] _2 KW[";"],
   Assignment                                     -- _1 KW["="] _2 KW[";"],
   LFieldAccess                                   -- _1 KW["."] _2,
   LTuple                                         -- KW["("] _1 KW[","] _2 KW[")"],
   LTuple.2:iter-star-sep                         -- _1 KW[","],
   LIndexer                                       -- _1 KW["["] _2 KW["]"],
   ExpStat                                        -- _1 KW[";"],
   If                                             -- KW["if"] KW["("] _1 KW[")"] _2 KW["else"] _3,
   IfNoElse                                       -- KW["if"] KW["("] _1 KW[")"] _2,
   For                                            -- KW["foreach"] KW["("] _1 KW[":"] _2 KW["in"] _3 KW[")"] KW["{"] _4 KW["}"],
   For.4:iter-star                                -- _1,
   ForInferred                                    -- KW["foreach"] KW["("] _1 KW["in"] _2 KW[")"] KW["{"] _3 KW["}"],
   ForInferred.3:iter-star                        -- _1,
   While                                          -- KW["while"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   While.2:iter-star                              -- _1,
   Block                                          -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   Block.1:iter-star                              -- _1,
   For                                            -- KW["for"] KW["("] _1 KW[":"] _2 KW["in"] _3 KW[")"] KW["{"] _4 KW["}"],
   For.4:iter-star                                -- _1,
   ForInferred                                    -- KW["for"] KW["("] _1 KW["in"] _2 KW[")"] KW["{"] _3 KW["}"],
   ForInferred.3:iter-star                        -- _1,
   Return                                         -- KW["return"] _1 KW[";"],
   ScreenReturn                                   -- KW["screen"] KW["return"] _1 KW[";"],
   Return                                         -- KW["return"] KW[";"],
   ScreenReturn                                   -- KW["screen"] KW["return"] KW[";"],
   Async                                          -- KW["async"] KW["{"] _1 KW["}"],
   Async.1:iter-star                              -- _1,
   String                                         -- _1,
   Num                                            -- _1,
   True                                           -- KW["true"],
   False                                          -- KW["false"],
   Null                                           -- KW["null"],
   This                                           -- KW["this"],
   Not                                            -- KW["!"] _1,
   Call                                           -- _1 KW["("] _2 KW[")"],
   Call.2:iter-star-sep                           -- _1 KW[","],
   Var                                            -- _1,
   Brackets                                       -- KW["("] _1 KW[")"],
   MethodCall                                     -- _1 KW["."] _2 KW["("] _3 KW[")"],
   MethodCall.3:iter-star-sep                     -- _1 KW[","],
   FieldAccess                                    -- _1 KW["."] _2,
   Indexer                                        -- _1 KW["["] _2 KW["]"],
   NamedExp                                       -- _1 KW["="] _2,
   BinMethodCall                                  -- _1 _2 _3,
   BinMethodCall                                  -- _1 _2 _3,
   BinMethodCall                                  -- _1 _2 _3,
   BinMethodCall                                  -- _1 _2 _3,
   Choice                                         -- _1 KW["?"] _2 KW[":"] _3,
   CollectionCons                                 -- _1 KW["<"] _2 KW[">"] KW["("] _3 KW[")"],
   CollectionCons.2:iter-star-sep                 -- _1 KW[","],
   CollectionCons.3:iter-star-sep                 -- _1 KW[","],
   EntityCons                                     -- _1 KW["{"] _2 KW["}"],
   EntityCons.2:iter-star-sep                     -- _1 KW[","],
   List                                           -- KW["["] _1 KW["]"],
   List.1:iter-star-sep                           -- _1 KW[","],
   Tuple                                          -- KW["("] _1 KW[","] _2 KW[")"],
   Tuple.2:iter-star-sep                          -- _1 KW[","],
   AsyncCall                                      -- KW["async"] KW["("] _1 KW[")"],
   AsyncCall.1:iter-star-sep                      -- _1 KW[","],
   Callback                                       -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   Callback.1:iter-star                           -- _1,
   AnonymousControl                               -- KW["control"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   AnonymousControl.1:iter-star-sep               -- _1 KW[","],
   AnonymousControl.2:iter-star                   -- _1,
   AnonymousFunctionNoReturnType                  -- KW["function"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   AnonymousFunctionNoReturnType.1:iter-star-sep  -- _1 KW[","],
   AnonymousFunctionNoReturnType.2:iter-star      -- _1,
   AnonymousFunction                              -- KW["function"] KW["("] _1 KW[")"] KW[":"] _2 KW["{"] _3 KW["}"],
   AnonymousFunction.1:iter-star-sep              -- _1 KW[","],
   AnonymousFunction.3:iter-star                  -- _1,
   PropVal                                        -- _1 KW["="] _2,
   ImportData                                     -- KW["$data"] KW["("] _1 KW[")"],
   SetComp                                        -- _1 _2,
   SetComp.2:iter                                 -- _1,
   WhereFilter                                    -- KW["where"] _1,
   OrderByFilter                                  -- KW["order"] KW["by"] _1,
   PrefetchFilter                                 -- V  [H  [KW["prefetch"]] _1],
   PrefetchFilter.1:iter-sep                      -- _1 KW[","],
   LimitFilter                                    -- KW["limit"] _1,
   OffsetFilter                                   -- KW["offset"] _1,
   OrderNonSpecific                               -- _1,
   OrderAscending                                 -- _1 KW["asc"],
   OrderDescending                                -- _1 KW["desc"],
   SetEq                                          -- _1 KW["=="] _2,
   SetNotEq                                       -- _1 KW["!="] _2,
   SetLt                                          -- _1 KW["<"] _2,
   SetLeq                                         -- _1 KW["<="] _2,
   SetGt                                          -- _1 KW[">"] _2,
   SetGeq                                         -- _1 KW[">="] _2,
   SetIn                                          -- _1 KW["in"] _2,
   SetNotIn                                       -- _1 KW["not"] KW["in"] _2,
   SetAnd                                         -- _1 KW["&&"] _2,
   Entity                                         -- _1 KW["entity"] _2 KW[":"] _3 KW["{"] _4 KW["}"],
   Entity.1:iter-star                             -- _1,
   Entity.4:iter-star                             -- _1,
   EntityNoSuper                                  -- _1 KW["entity"] _2 KW["{"] _3 KW["}"],
   EntityNoSuper.1:iter-star                      -- _1,
   EntityNoSuper.3:iter-star                      -- _1,
   Property                                       -- _1 _2 KW[":"] _3 KW["("] _4 KW[")"],
   Property.1:iter-star                           -- _1,
   Property.4:iter-star-sep                       -- _1 KW[","],
   PropertyNoAnnos                                -- _1 _2 KW[":"] _3,
   PropertyNoAnnos.1:iter-star                    -- _1,
   SimpleAnno                                     -- _1,
   InverseAnno                                    -- KW["inverse"] KW[":"] _1,
   SyncEntityAnno                                 -- KW["@sync"] _1,
   ScreenNoReturnType                             -- _1 KW["screen"] _2 KW["("] _3 KW[")"] KW["{"] _4 KW["}"],
   ScreenNoReturnType.1:iter-star                 -- _1,
   ScreenNoReturnType.3:iter-star-sep             -- _1 KW[","],
   ScreenNoReturnType.4:iter-star                 -- _1,
   Screen                                         -- _1 KW["screen"] _2 KW["("] _3 KW[")"] KW[":"] _4 KW["{"] _5 KW["}"],
   Screen.1:iter-star                             -- _1,
   Screen.3:iter-star-sep                         -- _1 KW[","],
   Screen.5:iter-star                             -- _1,
   Control                                        -- _1 KW["control"] _2 KW["("] _3 KW[")"] KW["{"] _4 KW["}"],
   Control.1:iter-star                            -- _1,
   Control.3:iter-star-sep                        -- _1 KW[","],
   Control.4:iter-star                            -- _1,
   Control                                        -- _1 KW["template"] _2 KW["("] _3 KW[")"] KW["{"] _4 KW["}"],
   Control.1:iter-star                            -- _1,
   Control.3:iter-star-sep                        -- _1 KW[","],
   Control.4:iter-star                            -- _1,
   ControlSig                                     -- _1 KW["("] _2 KW[")"],
   ControlSig.2:iter-star-sep                     -- _1 KW[","],
   Html                                           -- KW["<"] _1 _2 KW[">"] _3 KW["</"] _4 KW[">"],
   Html.2:iter-star                               -- _1,
   Html.3:iter-star                               -- _1,
   HtmlShort                                      -- KW["<"] _1 _2 KW["/"] KW[">"],
   HtmlShort.2:iter-star                          -- _1,
   NamedHtml                                      -- _1 KW["@"] KW["<"] _2 _3 KW[">"] _4 KW["</"] _5 KW[">"],
   NamedHtml.3:iter-star                          -- _1,
   NamedHtml.4:iter-star                          -- _1,
   NamedHtmlShort                                 -- _1 KW["@"] KW["<"] _2 _3 KW["/"] KW[">"],
   NamedHtmlShort.3:iter-star                     -- _1,
   HtmlArg                                        -- _1 KW["="] _2,
   HtmlDatabindArg                                -- KW["databind"] KW["="] _1,
   VarDecl                                        -- KW["var"] _1 KW[":"] _2 KW["="] _3,
   VarDeclInferred                                -- KW["var"] _1 KW["="] _2,
   DeriveDecl                                     -- KW["var"] _1 KW[":"] _2 KW["<-"] _3,
   DeriveDeclInferred                             -- KW["var"] _1 KW["<-"] _2,
   Script                                         -- KW["init"] KW["{"] _1 KW["}"],
   Script.1:iter-star                             -- _1,
   Script                                         -- KW["script"] KW["{"] _1 KW["}"],
   Script.1:iter-star                             -- _1,
   ScreenString                                   -- _1,
   List                                           -- KW["list"] KW["("] _1 KW[":"] _2 KW["in"] _3 KW[")"] KW["{"] _4 KW["}"],
   List.4:iter-star                               -- _1,
   ListInferred                                   -- KW["list"] KW["("] _1 KW["in"] _2 KW[")"] KW["{"] _3 KW["}"],
   ListInferred.3:iter-star                       -- _1,
   WhenNoElse                                     -- KW["cond"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   WhenNoElse.2:iter-star                         -- _1,
   When                                           -- KW["when"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"] KW["else"] KW["{"] _3 KW["}"],
   When.2:iter-star                               -- _1,
   When.3:iter-star                               -- _1,
   WhenNoElse                                     -- KW["when"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   WhenNoElse.2:iter-star                         -- _1,
   ScreenVarDecl                                  -- KW["var"] _1 KW[":"] _2 KW["="] _3,
   ControlCall                                    -- _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   ControlCall.2:iter-star-sep                    -- _1 KW[","],
   ControlCall.3:iter-star                        -- _1,
   ControlCallNoBody                              -- _1 KW["("] _2 KW[")"],
   ControlCallNoBody.2:iter-star-sep              -- _1 KW[","],
   ControlCallNoArgs                              -- _1 KW["{"] _2 KW["}"],
   ControlCallNoArgs.2:iter-star                  -- _1,
   QId                                            -- _1 KW["::"] _2,
   Module                                         -- KW["module"] _1 _2,
   Module.2:iter-star                             -- _1,
   Application                                    -- KW["application"] _1 _2,
   Application.2:iter-star                        -- _1,
   DynamicImport                                  -- KW["dynamic"] KW["import"] _1,
   Import                                         -- KW["import"] _1,
   Load                                           -- KW["load"] _1,
   Resource                                       -- KW["resource"] _1,
   Mixin                                          -- KW["mixin"] _1,
   FArg                                           -- _1 KW[":"] _2,
   FArgOptional                                   -- _1 KW[":"] _2 KW["="] _3,
   SimpleType                                     -- _1,
   GenericType                                    -- _1 KW["<"] _2 KW[">"],
   GenericType.2:iter-star-sep                    -- _1 KW[","],
   TupleType                                      -- KW["("] _1 KW[")"],
   TupleType.1:iter-star-sep                      -- _1 KW[","],
   ArrayType                                      -- KW["["] _1 KW["]"],
   DynamicType                                    -- KW["?"],
   FunctionType                                   -- _1 KW["->"] _2,
   FunctionType.1:iter-sep                        -- _1 KW["*"],
   DocAnno                                        -- KW["@doc"] _1,
   WhenAnno                                       -- KW["@when"] _1,
   PersistableAnno                                -- KW["@persistable"],
   DecoratorAnno                                  -- KW["@"] _1,
   Path                                           -- _1,
   Path.1:iter-sep                                -- _1 KW["/"],
   AbsolutePath                                   -- V  [H  [KW["/"]] _1],
   AbsolutePath.1:iter-sep                        -- _1 KW["/"],
   QuotedPath                                     -- _1,
   Javascript                                     -- KW["<javascript>"] _1 KW["</javascript>"],
   ModuleJavascript                               -- _1 KW["@<javascript>"] _2 KW["</javascript>"],
   JavascriptFor                                  -- KW["<javascript"] KW["for"] KW["="] _1 KW[">"] _2 KW["</javascript>"],
   ModuleJavascriptFor                            -- _1 KW["@<javascript"] KW["for"] KW["="] _2 KW[">"] _3 KW["</javascript>"],
   UriPath                                        -- V  [H  [KW["/"]] _1],
   UriPath.1:iter-star-sep                        -- _1 KW["/"],
   UriPart                                        -- _1,
   UriVar                                         -- KW[":"] _1
]